//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class Field {
    
    private string labelField;
    
    private string nameField;
    
    private string showField;
    
    private string orderField;
    
    private string formatField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class ContactInfo {
    
    private ContactInfoAddressContact[][] addressField;
    
    private ContactInfoEmail[] emailField;
    
    private ContactInfoTelephoneListTelephone[][] telephoneListField;
    
    private ContactInfoWebsite[] websiteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Contact", typeof(ContactInfoAddressContact), IsNullable=false)]
    public ContactInfoAddressContact[][] Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Email")]
    public ContactInfoEmail[] Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Telephone", typeof(ContactInfoTelephoneListTelephone), IsNullable=false)]
    public ContactInfoTelephoneListTelephone[][] TelephoneList {
        get {
            return this.telephoneListField;
        }
        set {
            this.telephoneListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Website")]
    public ContactInfoWebsite[] Website {
        get {
            return this.websiteField;
        }
        set {
            this.websiteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class ContactInfoAddressContact {
    
    private string addressLineField;
    
    private string postalCodeField;
    
    private string municipalityField;
    
    private ContactInfoAddressContactCountry[] countryField;
    
    /// <remarks/>
    public string AddressLine {
        get {
            return this.addressLineField;
        }
        set {
            this.addressLineField = value;
        }
    }
    
    /// <remarks/>
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Municipality {
        get {
            return this.municipalityField;
        }
        set {
            this.municipalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Country")]
    public ContactInfoAddressContactCountry[] Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class ContactInfoAddressContactCountry {
    
    private string codeField;
    
    private string labelField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class ContactInfoEmail {
    
    private string contactField;
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class ContactInfoTelephoneListTelephone {
    
    private string contactField;
    
    private Use[] useField;
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Use")]
    public Use[] Use {
        get {
            return this.useField;
        }
        set {
            this.useField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class Use {
    
    private string codeField;
    
    private string labelField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class ContactInfoWebsite {
    
    private string contactField;
    
    private Use[] useField;
    
    /// <remarks/>
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Use")]
    public Use[] Use {
        get {
            return this.useField;
        }
        set {
            this.useField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class Description {
    
    private string labelField;
    
    private string codeField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class Period {
    
    private string currentField;
    
    private PeriodFrom[] fromField;
    
    private PeriodTO[] toField;
    
    /// <remarks/>
    public string Current {
        get {
            return this.currentField;
        }
        set {
            this.currentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("From")]
    public PeriodFrom[] From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("To")]
    public PeriodTO[] To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class PeriodFrom {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class PeriodTO {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class SkillsPassport {
    
    private SkillsPassportDocumentInfo[] documentInfoField;
    
    private SkillsPassportPrintingPreferencesDocument[][] printingPreferencesField;
    
    private SkillsPassportLearnerInfo[] learnerInfoField;
    
    private string localeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentInfo")]
    public SkillsPassportDocumentInfo[] DocumentInfo {
        get {
            return this.documentInfoField;
        }
        set {
            this.documentInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", typeof(SkillsPassportPrintingPreferencesDocument), IsNullable=false)]
    public SkillsPassportPrintingPreferencesDocument[][] PrintingPreferences {
        get {
            return this.printingPreferencesField;
        }
        set {
            this.printingPreferencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LearnerInfo")]
    public SkillsPassportLearnerInfo[] LearnerInfo {
        get {
            return this.learnerInfoField;
        }
        set {
            this.learnerInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locale {
        get {
            return this.localeField;
        }
        set {
            this.localeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportDocumentInfo {
    
    private string documentTypeField;
    
    private string creationDateField;
    
    private string lastUpdateDateField;
    
    private string xSDVersionField;
    
    private string generatorField;
    
    private string commentField;
    
    /// <remarks/>
    public string DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public string CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    public string LastUpdateDate {
        get {
            return this.lastUpdateDateField;
        }
        set {
            this.lastUpdateDateField = value;
        }
    }
    
    /// <remarks/>
    public string XSDVersion {
        get {
            return this.xSDVersionField;
        }
        set {
            this.xSDVersionField = value;
        }
    }
    
    /// <remarks/>
    public string Generator {
        get {
            return this.generatorField;
        }
        set {
            this.generatorField = value;
        }
    }
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportPrintingPreferencesDocument {
    
    private Field[] fieldField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public Field[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfo {
    
    private SkillsPassportLearnerInfoIdentification[] identificationField;
    
    private SkillsPassportLearnerInfoHeadline[] headlineField;
    
    private SkillsPassportLearnerInfoWorkExperienceListWorkExperience[][] workExperienceListField;
    
    private SkillsPassportLearnerInfoEducationListEducation[][] educationListField;
    
    private SkillsPassportLearnerInfoSkills[] skillsField;
    
    private SkillsPassportLearnerInfoAchievementListAchievement[][] achievementListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Identification")]
    public SkillsPassportLearnerInfoIdentification[] Identification {
        get {
            return this.identificationField;
        }
        set {
            this.identificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Headline")]
    public SkillsPassportLearnerInfoHeadline[] Headline {
        get {
            return this.headlineField;
        }
        set {
            this.headlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkExperience", typeof(SkillsPassportLearnerInfoWorkExperienceListWorkExperience), IsNullable=false)]
    public SkillsPassportLearnerInfoWorkExperienceListWorkExperience[][] WorkExperienceList {
        get {
            return this.workExperienceListField;
        }
        set {
            this.workExperienceListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Education", typeof(SkillsPassportLearnerInfoEducationListEducation), IsNullable=false)]
    public SkillsPassportLearnerInfoEducationListEducation[][] EducationList {
        get {
            return this.educationListField;
        }
        set {
            this.educationListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Skills")]
    public SkillsPassportLearnerInfoSkills[] Skills {
        get {
            return this.skillsField;
        }
        set {
            this.skillsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Achievement", typeof(SkillsPassportLearnerInfoAchievementListAchievement), IsNullable=false)]
    public SkillsPassportLearnerInfoAchievementListAchievement[][] AchievementList {
        get {
            return this.achievementListField;
        }
        set {
            this.achievementListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentification {
    
    private SkillsPassportLearnerInfoIdentificationPersonName[] personNameField;
    
    private ContactInfo[] contactInfoField;
    
    private SkillsPassportLearnerInfoIdentificationDemographics[] demographicsField;
    
    private SkillsPassportLearnerInfoIdentificationPhoto[] photoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PersonName")]
    public SkillsPassportLearnerInfoIdentificationPersonName[] PersonName {
        get {
            return this.personNameField;
        }
        set {
            this.personNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInfo")]
    public ContactInfo[] ContactInfo {
        get {
            return this.contactInfoField;
        }
        set {
            this.contactInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Demographics")]
    public SkillsPassportLearnerInfoIdentificationDemographics[] Demographics {
        get {
            return this.demographicsField;
        }
        set {
            this.demographicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Photo")]
    public SkillsPassportLearnerInfoIdentificationPhoto[] Photo {
        get {
            return this.photoField;
        }
        set {
            this.photoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationPersonName {
    
    private string firstNameField;
    
    private string surnameField;
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationDemographics {
    
    private SkillsPassportLearnerInfoIdentificationDemographicsBirthdate[] birthdateField;
    
    private SkillsPassportLearnerInfoIdentificationDemographicsNationalityListNationality[][] nationalityListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Birthdate")]
    public SkillsPassportLearnerInfoIdentificationDemographicsBirthdate[] Birthdate {
        get {
            return this.birthdateField;
        }
        set {
            this.birthdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Nationality", typeof(SkillsPassportLearnerInfoIdentificationDemographicsNationalityListNationality), IsNullable=false)]
    public SkillsPassportLearnerInfoIdentificationDemographicsNationalityListNationality[][] NationalityList {
        get {
            return this.nationalityListField;
        }
        set {
            this.nationalityListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationDemographicsBirthdate {
    
    private string yearField;
    
    private string monthField;
    
    private string dayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationDemographicsNationalityListNationality {
    
    private string codeField;
    
    private string labelField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationPhoto {
    
    private string mimeTypeField;
    
    private string dataField;
    
    private SkillsPassportLearnerInfoIdentificationPhotoMetadataListMetadata[][] metadataListField;
    
    /// <remarks/>
    public string MimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Metadata", typeof(SkillsPassportLearnerInfoIdentificationPhotoMetadataListMetadata), IsNullable=false)]
    public SkillsPassportLearnerInfoIdentificationPhotoMetadataListMetadata[][] MetadataList {
        get {
            return this.metadataListField;
        }
        set {
            this.metadataListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoIdentificationPhotoMetadataListMetadata {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoHeadline {
    
    private SkillsPassportLearnerInfoHeadlineType[] typeField;
    
    private Description[] descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Type")]
    public SkillsPassportLearnerInfoHeadlineType[] Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public Description[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoHeadlineType {
    
    private string codeField;
    
    private string labelField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoWorkExperienceListWorkExperience {
    
    private string activitiesField;
    
    private Period[] periodField;
    
    private SkillsPassportLearnerInfoWorkExperienceListWorkExperiencePosition[] positionField;
    
    private SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployer[] employerField;
    
    /// <remarks/>
    public string Activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Period")]
    public Period[] Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Position")]
    public SkillsPassportLearnerInfoWorkExperienceListWorkExperiencePosition[] Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Employer")]
    public SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployer[] Employer {
        get {
            return this.employerField;
        }
        set {
            this.employerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoWorkExperienceListWorkExperiencePosition {
    
    private string labelField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployer {
    
    private string nameField;
    
    private ContactInfo[] contactInfoField;
    
    private SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployerSector[] sectorField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInfo")]
    public ContactInfo[] ContactInfo {
        get {
            return this.contactInfoField;
        }
        set {
            this.contactInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sector")]
    public SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployerSector[] Sector {
        get {
            return this.sectorField;
        }
        set {
            this.sectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoWorkExperienceListWorkExperienceEmployerSector {
    
    private string labelField;
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoEducationListEducation {
    
    private string titleField;
    
    private string activitiesField;
    
    private Period[] periodField;
    
    private SkillsPassportLearnerInfoEducationListEducationOrganisation[] organisationField;
    
    private Field[] fieldField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Period")]
    public Period[] Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Organisation")]
    public SkillsPassportLearnerInfoEducationListEducationOrganisation[] Organisation {
        get {
            return this.organisationField;
        }
        set {
            this.organisationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public Field[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoEducationListEducationOrganisation {
    
    private string nameField;
    
    private ContactInfo[] contactInfoField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInfo")]
    public ContactInfo[] ContactInfo {
        get {
            return this.contactInfoField;
        }
        set {
            this.contactInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkills {
    
    private SkillsPassportLearnerInfoSkillsLinguistic[] linguisticField;
    
    private SkillsPassportLearnerInfoSkillsCommunication[] communicationField;
    
    private SkillsPassportLearnerInfoSkillsOrganisational[] organisationalField;
    
    private SkillsPassportLearnerInfoSkillsJobRelated[] jobRelatedField;
    
    private SkillsPassportLearnerInfoSkillsComputer[] computerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Linguistic")]
    public SkillsPassportLearnerInfoSkillsLinguistic[] Linguistic {
        get {
            return this.linguisticField;
        }
        set {
            this.linguisticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Communication")]
    public SkillsPassportLearnerInfoSkillsCommunication[] Communication {
        get {
            return this.communicationField;
        }
        set {
            this.communicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Organisational")]
    public SkillsPassportLearnerInfoSkillsOrganisational[] Organisational {
        get {
            return this.organisationalField;
        }
        set {
            this.organisationalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("JobRelated")]
    public SkillsPassportLearnerInfoSkillsJobRelated[] JobRelated {
        get {
            return this.jobRelatedField;
        }
        set {
            this.jobRelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Computer")]
    public SkillsPassportLearnerInfoSkillsComputer[] Computer {
        get {
            return this.computerField;
        }
        set {
            this.computerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsLinguistic {
    
    private Description[][][] motherTongueListField;
    
    private SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguage[][] foreignLanguageListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("MotherTongue", typeof(Description[]), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(Description), IsNullable=false, NestingLevel=1)]
    public Description[][][] MotherTongueList {
        get {
            return this.motherTongueListField;
        }
        set {
            this.motherTongueListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ForeignLanguage", typeof(SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguage), IsNullable=false)]
    public SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguage[][] ForeignLanguageList {
        get {
            return this.foreignLanguageListField;
        }
        set {
            this.foreignLanguageListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguage {
    
    private Description[] descriptionField;
    
    private SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageProficiencyLevel[] proficiencyLevelField;
    
    private SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageVerifiedByCertificate[][] verifiedByField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Description")]
    public Description[] Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ProficiencyLevel")]
    public SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageProficiencyLevel[] ProficiencyLevel {
        get {
            return this.proficiencyLevelField;
        }
        set {
            this.proficiencyLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Certificate", typeof(SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageVerifiedByCertificate), IsNullable=false)]
    public SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageVerifiedByCertificate[][] VerifiedBy {
        get {
            return this.verifiedByField;
        }
        set {
            this.verifiedByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageProficiencyLevel {
    
    private string listeningField;
    
    private string readingField;
    
    private string spokenInteractionField;
    
    private string spokenProductionField;
    
    private string writingField;
    
    /// <remarks/>
    public string Listening {
        get {
            return this.listeningField;
        }
        set {
            this.listeningField = value;
        }
    }
    
    /// <remarks/>
    public string Reading {
        get {
            return this.readingField;
        }
        set {
            this.readingField = value;
        }
    }
    
    /// <remarks/>
    public string SpokenInteraction {
        get {
            return this.spokenInteractionField;
        }
        set {
            this.spokenInteractionField = value;
        }
    }
    
    /// <remarks/>
    public string SpokenProduction {
        get {
            return this.spokenProductionField;
        }
        set {
            this.spokenProductionField = value;
        }
    }
    
    /// <remarks/>
    public string Writing {
        get {
            return this.writingField;
        }
        set {
            this.writingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsLinguisticForeignLanguageListForeignLanguageVerifiedByCertificate {
    
    private string titleField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsCommunication {
    
    private string descriptionField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsOrganisational {
    
    private string descriptionField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsJobRelated {
    
    private string descriptionField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoSkillsComputer {
    
    private string descriptionField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
public partial class SkillsPassportLearnerInfoAchievementListAchievement {
    
    private string descriptionField;
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://europass.cedefop.europa.eu/Europass")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://europass.cedefop.europa.eu/Europass", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContactInfo", typeof(ContactInfo))]
    [System.Xml.Serialization.XmlElementAttribute("Description", typeof(Description))]
    [System.Xml.Serialization.XmlElementAttribute("Field", typeof(Field))]
    [System.Xml.Serialization.XmlElementAttribute("Period", typeof(Period))]
    [System.Xml.Serialization.XmlElementAttribute("SkillsPassport", typeof(SkillsPassport))]
    [System.Xml.Serialization.XmlElementAttribute("Use", typeof(Use))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
